#' Summarize Fitted Models for Batch-Effect Diagnostics
#'
#' Extracts model coefficients and constructs residual representations used
#' for diagnosing additive and multiplicative batch effects. The appropriate
#' method is selected automatically according to the class of `diag_model`.
#'
#' @param diag_model A fitted diagnostic-model object returned by
#'   [diag_model_gen()].
#'
#' @param ... Additional arguments passed to the corresponding S3 method.
#'
#' @return An object of class `"diag_summary"` containing:
#' \describe{
#'   \item{coef}{
#'     Estimated model coefficients for each feature.
#'   }
#'   \item{resid_add}{
#'     A matrix of observations after removal of the modeled non-batch
#'     mean structure. Batch-related mean variation is retained, making this
#'     representation suitable for assessing additive batch effects.
#'   }
#'   \item{resid_mul}{
#'     A matrix of ordinary model residuals after removal of the full fitted
#'     mean structure, including modeled batch effects. This representation
#'     can be used to assess residual scale or variance-related batch effects.
#'   }
#' }
#'
#' @details
#' `diag_model_summary()` is an S3 generic. Methods are provided for
#' linear models, generalized additive models, and linear mixed-effects
#' models generated by [diag_model_gen()].
#'
#' For linear and generalized additive models, `resid_add` is obtained by
#' reconstructing the fitted contribution of all model terms except terms
#' whose names begin with `"batch"`, and subtracting this contribution from
#' the observed data.
#'
#' For linear mixed-effects models, `resid_add` removes the selected
#' non-batch fixed effects together with the specified random-intercept
#' contributions. The ordinary model residuals are stored in `resid_mul`.
#'
#' @seealso
#' [diag_model_gen()]
#'
#' @export
diag_model_summary <- function(diag_model, ...) {
  UseMethod("diag_model_summary")
}

#' @rdname diag_model_summary
#'
#' @method diag_model_summary lm_model
#'
#' @export
diag_model_summary.lm_model <- function(diag_model, ...){
  fits <- diag_model$fits
  Y <- as.matrix(diag_model$data)
  coefs <- lapply(fits, coef)
  fix_list <- lapply(fits, function(model) {
    X <- stats::model.matrix(model)
    beta <- stats::coef(model)
    X <- X[, !grepl("^batch", colnames(X)), drop = FALSE]
    beta <- beta[!grepl("^batch", names(beta))]
    common <- intersect(colnames(X), names(beta))
    if (length(common) == 0) {
      return(numeric(nrow(Y)))
    }
    missing <- setdiff(colnames(X), names(beta))
    if (length(missing) > 0) {
      stop("Missing coefficient(s) for: ", paste(missing, collapse = ", "))
    }
    as.numeric(X[, common, drop = FALSE] %*% beta[common])
  })
  fix_effects <- do.call(cbind, fix_list)
  if (nrow(Y) != nrow(fix_effects)) {
    stop("Row mismatch: nrow(data) != nobs in lm fits.")
  }
  resid_add <- Y - fix_effects
  resid_mul <- sapply(fits, resid, simplify = "matrix")
  diag_summary <- list(coef = coefs, resid_add = resid_add, resid_mul = resid_mul)
  class(diag_summary) <- "diag_summary"
  return(diag_summary)
}


#' @rdname diag_model_summary
#'
#' @method diag_model_summary gam_model
#'
#' @export
diag_model_summary.gam_model <- function(diag_model, ...){
  fits <- diag_model$fits
  Y <- diag_model$data
  coefs <- lapply(fits, coef)
  fix_list <- lapply(fits, function(model) {
    X <- stats::model.matrix(model)
    beta <- stats::coef(model)
    keep_X <- !grepl("^batch", colnames(X))
    X <- X[, keep_X, drop = FALSE]
    keep_b <- !grepl("^batch", names(beta))
    beta <- beta[keep_b]
    common <- intersect(colnames(X), names(beta))
    if (length(common) == 0) {
      stop("No overlapping terms between model.matrix and coefficients after filtering.")
    }
    if (length(common) != ncol(X)) {
      missing <- setdiff(colnames(X), names(beta))
      if (length(missing) > 0) {
        stop("Missing coefficient(s) for: ", paste(missing, collapse = ", "))
      }
      X <- X[, common, drop = FALSE]
    }
    as.numeric(X %*% beta[common])
  })
  fix_effects <- do.call(cbind, fix_list)
  Y_mat <- as.matrix(Y)
  if (nrow(Y_mat) != nrow(fix_effects)) {
    stop("Row mismatch: nrow(data) != nobs in GAM fits.")
  }
  resid_add <- Y_mat - fix_effects
  resid_mul <- sapply(fits, resid, simplify = "matrix")
  diag_summary <- list(coef = coefs, resid_add = resid_add, resid_mul = resid_mul)
  class(diag_summary) <- "diag_summary"
  return(diag_summary)
}

#' @rdname diag_model_summary
#'
#' @param random Character vector specifying the grouping factors whose
#'   random-intercept contributions should be removed when constructing
#'   `resid_add`. Each name must correspond to a grouping factor present
#'   in the fitted mixed-effects models.
#'
#' @method diag_model_summary lmerMod_model
#'
#' @export
diag_model_summary.lmerMod_model <- function(diag_model, random, ...){
  fits <- diag_model$fits
  Y    <- diag_model$data
  df   <- diag_model$mod
  coefs <- sapply(fits, function(m) lme4::fixef(m), simplify = "matrix")
  if (!is.character(random) || length(random) == 0) {
    stop("`random` must be a non-empty character vector of grouping-factor names.")
  }
  rand_mat <- sapply(fits, function(m) {
    N <- nrow(df)
    add_total <- numeric(N)
    re_all <- lme4::ranef(m)
    for (r in random) {
      if (!r %in% names(re_all)) {
        stop("Grouping factor `", r, "` not found in ranef(model). Available: ",
             paste(names(re_all), collapse = ", "))
      }
      re_mat <- re_all[[r]]
      if (!"(Intercept)" %in% colnames(re_mat)) {
        stop("Random intercept not found for grouping factor: ", r)
      }
      ids <- as.character(df[[r]])
      idx <- match(ids, rownames(re_mat))
      add <- numeric(N)
      ok <- !is.na(idx)
      add[ok] <- re_mat[idx[ok], "(Intercept)"]
      add_total <- add_total + add
    }
    add_total
  })
  rand_mat <- as.matrix(rand_mat)
  X <- lme4::getME(fits[[1]], "X")
  keep <- !grepl("^batch", colnames(X))
  X <- X[, keep, drop = FALSE]
  X <- X[, colnames(X) != "(Intercept)", drop = FALSE]
  common <- intersect(colnames(X), rownames(coefs))
  if (length(common) != ncol(X)) {
    missing <- setdiff(colnames(X), rownames(coefs))
    stop("Coefficient(s) missing for X columns: ", paste(missing, collapse = ", "))
  }
  B <- coefs[common, , drop = FALSE]
  B <- apply(B, 2, as.numeric)
  resid_add <- Y - (X[, common, drop = FALSE] %*% B + rand_mat)
  resid_mul <- sapply(fits, resid, simplify = "matrix")
  diag_summary <- list(coef = coefs, resid_add = resid_add, resid_mul = resid_mul)
  class(diag_summary) <- "diag_summary"
  return(diag_summary)
}


#' Fit Feature-Wise Models for Batch Diagnostics
#'
#' Fits a separate regression model to each feature and constructs an
#' object suitable for use with [diag_model_summary()].
#'
#' @param bat A vector specifying the batch membership of each observation.
#'
#' @param data A numeric matrix or data frame with observations in rows and
#'   features in columns.
#'
#' @param covar Optional data frame containing covariates to include in the
#'   feature-wise models.
#'
#' @param model A model-fitting function, such as [stats::lm()],
#'   [mgcv::gam()], or [lme4::lmer()].
#'
#' @param formula A model formula specifying the covariate structure.
#'   Its exact form depends on the supplied `model`.
#'
#' @param ref.batch Optional reference batch used when constructing the batch
#'   design matrix. Defaults to `NULL`.
#'
#' @param bat_adjust Logical indicating whether batch terms should be included
#'   in the fitted models. Defaults to `TRUE`.
#'
#' @param ... Additional arguments passed to the model-fitting function.
#'
#' @return A fitted model object with an S3 class determined by the underlying
#'   model type. The resulting object can be passed to
#'   [diag_model_summary()].
#'
#'
#' @seealso
#' [diag_model_summary()]
diag_model_gen <- function(bat, data, covar, model, formula = NULL, ref.batch = NULL, bat_adjust = TRUE, ...){
  if (bat_adjust){
    batch_result <- batch_matrix(bat, ref.batch = ref.batch)
    fitted_model <- model_fitting(data, batch_result$batch_matrix, covar, model, formula, ...)
    class_type <- class(fitted_model$fits[[1]])
  }else{
    fits <- apply(data, 2, function(y) {
      if(is.null(covar)){
        dat <- data.frame(y = y)}else{
          dat <- data.frame(y = y, covar)
        }
      do.call(model, list(formula = formula, data = dat, ...))
    })
    fitted_model <- list(data = data, fits = unname(as.list(fits)))
    names(fitted_model$fits) <- colnames(data)
    class_type <- class(fits[[1]])
  }
  class(fitted_model) <- paste0(class_type[1], "_model")
  return(fitted_model)
}


#' Test for Batch Effects Across Features
#'
#' Compares full and reduced feature-wise models to test whether the `batch`
#' term significantly contributes to model fit. P-values are adjusted across
#' features using the Bonferroni method.
#'
#' @param diag_model A fitted diagnostic-model object containing one fitted
#'   model per feature. Supported models are `lm`, `gam`, and `lmerMod`.
#'
#' @param batch Batch variable used in the fitted models.
#'
#' @return A list containing:
#' \describe{
#'   \item{test_table}{
#'     A data frame with feature names, raw p-values, and Bonferroni-adjusted
#'     p-values.
#'   }
#'   \item{perc.sig}{
#'     Percentage of features with adjusted p-values below 0.05.
#'   }
#' }
#'
#' @details
#' For each feature, the full model is compared with a reduced model excluding
#' the `batch` term. F-tests are used for `lm` and `gam` models, and a
#' likelihood-ratio test is used for `lmerMod` models. Non-finite p-values are
#' replaced by 1.
#'
#' @export
anova_test <- function(diag_model, batch) {
  fits <- diag_model$fits
  p_raw <- sapply(fits, function(fit) {
    full_model <- fit
    reduced_model <- update(full_model, . ~ . - batch)

    if (inherits(full_model, "gam")) {
      anova_tab <- mgcv::anova.gam(reduced_model, full_model, test = "F")
      pval <- anova_tab[["Pr(>F)"]][2]
    } else if (inherits(full_model, "lm")) {
      anova_tab <- stats::anova(reduced_model, full_model, test = "F")
      pval <- anova_tab[["Pr(>F)"]][2]
    } else if (inherits(full_model, "lmerMod")) {
      anova_tab <- stats::anova(reduced_model, full_model, refit = TRUE)
      pval <- anova_tab[["Pr(>Chisq)"]][2]
    } else {
      stop("`anova_test()` currently supports only `lm`, `gam`, and `lmerMod` models.")
    }

    if (length(pval) != 1L || !is.finite(pval)) {pval <- 1}
    as.numeric(pval)
  })

  p_adj <- stats::p.adjust(p_raw, method = "bonferroni")

  percent_below_0.05 <- mean(p_adj < 0.05, na.rm = TRUE) * 100

  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")

  test_result <- data.frame(feature = names(fits), p_value_raw = as.numeric(p_raw), p_value = as.numeric(p_adj), row.names = NULL)

  return(list(test_table = test_result, perc.sig = num_sig))
}

#' Kenward-Roger Test for Batch Effects
#'
#' Tests the contribution of the `batch` term in feature-wise linear
#' mixed-effects models using the Kenward-Roger approximation. P-values are
#' adjusted across features using the Bonferroni method.
#'
#' @param diag_model A fitted diagnostic-model object containing one
#'   mixed-effects model per feature.
#'
#' @param batch Batch variable used in the fitted models.
#'
#' @param ... Additional arguments.
#'
#' @return A list containing:
#' \describe{
#'   \item{test_table}{
#'     A data frame with feature names and Bonferroni-adjusted p-values.
#'   }
#'   \item{perc.sig}{
#'     Percentage of features with adjusted p-values below 0.05.
#'   }
#' }
#'
#' @details
#' For each feature, the full model is compared with a reduced model excluding
#' the `batch` term using a Kenward-Roger test.
#'
#' @export
kenward_test <- function(diag_model, batch, ...){
  fits <- diag_model$fits
  p_value <- sapply(fits, function(fit){
    lmm1 <- fit
    lmm2 <- update(fit, . ~ . - batch)
    kr.test <- KRmodcomp(lmm1, lmm2) %>% tidy() %>% pull(.data[["p.value"]])
    return(kr.test)
  }) |> p.adjust(method = "bonferroni") |> round(3)
  test_result <- data.frame(cbind(feature = names(fits), p_value))
  percent_below_0.05 <- mean(p_value < 0.05) * 100
  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")
  return(list(test_table = test_result, perc.sig = num_sig))
}

#' Kruskal-Wallis Test for Additive Batch Effects
#'
#' Tests for differences in feature-wise additive residual distributions
#' across batches using the Kruskal-Wallis test. P-values are adjusted using
#' the Bonferroni method.
#'
#' @param resid_add A numeric matrix of additive residuals, with observations
#'   in rows and features in columns.
#'
#' @param batch A vector specifying batch membership for each observation.
#'
#' @return A list containing a table of Bonferroni-adjusted p-values and the
#'   percentage of features with adjusted p-values below 0.05.
#'
#' @export
kruskal_test <- function(resid_add, batch){
  G <- ncol(resid_add)
  p_value <- sapply(1:G, function(g) kruskal.test(resid_add[,g] ~ batch) %>% tidy() %>% pull(.data[["p.value"]])) |> p.adjust(method = "bonferroni") |> round(3)
  test_result <- data.frame(cbind(feature = colnames(resid_add), p_value))
  percent_below_0.05 <- mean(p_value < 0.05) * 100
  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")
  return(list(test_table = test_result, perc.sig = num_sig))
}

#' Levene Test for Variance Batch Effects
#'
#' Tests for differences in feature-wise residual variance across batches
#' using Levene's test. P-values are adjusted using the Bonferroni method.
#'
#' @param resid_mul A numeric matrix of model residuals, with observations
#'   in rows and features in columns.
#'
#' @param batch A vector specifying batch membership for each observation.
#'
#' @return A list containing a table of Bonferroni-adjusted p-values and the
#'   percentage of features with adjusted p-values below 0.05.
#'
#' @export
lv_test <- function(resid_mul, batch){
  G <- ncol(resid_mul)
  p_value <- sapply(1:G, function(g) leveneTest(resid_mul[,g] ~ batch) %>% tidy() %>% pull(.data[["p.value"]])) |> p.adjust(method = "bonferroni") |> round(3)
  test_result <- data.frame(cbind(feature = colnames(resid_mul), p_value))
  percent_below_0.05 <- mean(p_value < 0.05) * 100
  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")
  return(list(test_table = test_result, perc.sig = num_sig))
}

#' Bartlett Test for Variance Batch Effects
#'
#' Tests for differences in feature-wise residual variance across batches
#' using Bartlett's test. P-values are adjusted using the Bonferroni method.
#'
#' @param resid_mul A numeric matrix of model residuals, with observations
#'   in rows and features in columns.
#'
#' @param batch A vector specifying batch membership for each observation.
#'
#' @return A list containing a table of Bonferroni-adjusted p-values and the
#'   percentage of features with adjusted p-values below 0.05.
#'
#' @export
bl_test <- function(resid_mul, batch){
  G <- ncol(resid_mul)
  p_value <- sapply(1:G, function(g) bartlett.test(resid_mul[,g] ~ batch) %>% tidy() %>% pull(.data[["p.value"]])) |> p.adjust(method = "bonferroni") |> round(3)
  test_result <- data.frame(cbind(feature = colnames(resid_mul), p_value))
  percent_below_0.05 <- mean(p_value < 0.05) * 100
  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")
  return(list(test_table = test_result, perc.sig = num_sig))
}


#' Fligner-Killeen Test for Variance Batch Effects
#'
#' Tests for differences in feature-wise residual variance across batches
#' using the Fligner-Killeen test. P-values are adjusted using the Bonferroni
#' method.
#'
#' @param resid_mul A numeric matrix of model residuals, with observations
#'   in rows and features in columns.
#'
#' @param batch A vector specifying batch membership for each observation.
#'
#' @return A list containing a table of Bonferroni-adjusted p-values and the
#'   percentage of features with adjusted p-values below 0.05.
#'
#' @export
fk_test <- function(resid_mul, batch){
  G <- ncol(resid_mul)
  p_value <- sapply(1:G, function(g) fligner.test(resid_mul[,g] ~ batch) %>% tidy() %>% pull(.data[["p.value"]])) |> p.adjust(method = "bonferroni") |> round(3)
  test_result <- data.frame(cbind(feature = colnames(resid_mul), p_value))
  percent_below_0.05 <- mean(p_value < 0.05) * 100
  num_sig <- paste0(sprintf("%.2f", percent_below_0.05), "%")
  return(list(test_table = test_result, perc.sig = num_sig))
}

#' Prepare PCA Scores for Batch Diagnostics
#'
#' Fits feature-wise models, extracts additive residuals, and performs PCA on
#' the residual matrix for visualization of batch-related structure.
#'
#' @param bat A vector specifying batch or site membership.
#' @param data A numeric matrix or data frame with observations in rows and
#'   features in columns.
#' @param covar Optional data frame of covariates included in the fitted models.
#' @param model Model-fitting function used for feature-wise regression.
#' @param formula Optional model formula.
#' @param ref.batch Optional reference batch.
#' @param bat_adjust Logical indicating whether batch effects are included in
#'   model fitting.
#' @param test_param A list of additional arguments passed to
#'   [diag_model_summary()], such as random-effect grouping factors.
#' @param ... Additional arguments passed to the model-fitting procedure.
#'
#' @return A list containing the PCA score matrix `F_t` and the batch vector
#'   `bat`.
#'
#' @export
pca_prep <- function(bat, data, covar, model, formula = NULL, ref.batch = NULL, bat_adjust = TRUE, test_param = list(random = NULL), ...){
  if(is.data.frame(data) || is.matrix(data)){
    diag_model_result <- diag_model_gen(
      bat, data, covar, model, formula, ref.batch, bat_adjust, ...
    )
    diag_summary <- do.call(diag_model_summary, c(list(diag_model = diag_model_result), test_param))
    resid_add_df <- diag_summary$resid_add
    F_t <- prcomp(resid_add_df, center = TRUE, scale. = TRUE)$x
    return(list(F_t = F_t, bat = bat))
  }else{
    stop("`data` must be a data.frame, matrix, or a list of those.")
  }
}


#' Plot PCA Scores by Batch
#'
#' Creates a scatter plot of two selected principal components, colored by
#' batch or site.
#'
#' @param pca_prep_result An object returned by [pca_prep()].
#' @param type Character specifying the plot type. Currently retained for
#'   compatibility but not used.
#' @param pc_1 Integer specifying the principal component for the x-axis.
#'   Defaults to `1`.
#' @param pc_2 Integer specifying the principal component for the y-axis.
#'   Defaults to `2`.
#' @param ellipse Logical indicating whether to display batch-specific
#'   68-percent concentration ellipses. Defaults to `TRUE`.
#'
#' @return A `ggplot` object.
#'
#' @export
pca_plot <- function(pca_prep_result, type = "within", pc_1 = 1, pc_2 = 2, ellipse = TRUE){
  pc_pair <- paste0("PC", c(pc_1, pc_2))
  element_names <- names(pca_prep_result)
  F_df <- pca_prep_result$F_t %>% data.frame() %>% mutate(bat = pca_prep_result$bat)
  plt <- ggplot(
    F_df,
    aes(x = .data[[pc_pair[1]]], y = .data[[pc_pair[2]]], color = .data[["bat"]])
  ) +
    geom_point(alpha = 0.7, size = 1.6, stroke = 0) +
    coord_equal() +
    labs(
      x = pc_pair[1],
      y = pc_pair[2],
      color = "Batch / Site"
    ) +
    scale_color_brewer(palette = "Set2") +
    theme_minimal(base_size = 12) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(linewidth = 0.2),
      strip.text = element_text(face = "bold"),
      strip.background = element_rect(fill = "grey95", color = NA),
      legend.position = "bottom",
      legend.title = element_text(face = "bold"),
      plot.title.position = "plot",
      panel.spacing = unit(6, "pt"),
      axis.title = element_text(face = "bold")
    )
  if(ellipse){
    plt + stat_ellipse(level = 0.68, linewidth = 0.6, show.legend = FALSE)
  }else{
    plt
  }

}

#' Prepare t-SNE Embedding for Batch Diagnostics
#'
#' Fits feature-wise models, extracts additive residuals, and computes a
#' two-dimensional t-SNE embedding for visualization of batch-related
#' structure.
#'
#' @param bat A vector specifying batch or site membership.
#' @param data A numeric matrix or data frame with observations in rows and
#'   features in columns.
#' @param covar Optional data frame of covariates included in the fitted models.
#' @param model Model-fitting function used for feature-wise regression.
#' @param formula Optional model formula.
#' @param ref.batch Optional reference batch.
#' @param bat_adjust Logical indicating whether batch effects are included in
#'   model fitting.
#' @param test_param A list of additional arguments passed to
#'   [diag_model_summary()].
#' @param ... Additional arguments passed to the model-fitting procedure.
#'
#' @return A data frame containing the two t-SNE dimensions and batch
#'   membership.
#'
#' @export
tsne_prep <- function(bat, data, covar, model, formula = NULL, ref.batch = NULL, bat_adjust = TRUE, test_param = list(random = NULL), ...){
  if(is.data.frame(data) || is.matrix(data)){
    diag_model_result <- diag_model_gen(
      bat, data, covar, model, formula, ref.batch, bat_adjust, ...
    )
    diag_summary <- do.call(diag_model_summary, c(list(diag_model = diag_model_result), test_param))
    resid_add_df <- diag_summary$resid_add
    ts <- Rtsne::Rtsne(resid_add_df)
    df <- data.frame(
      dim1 = ts$Y[,1],
      dim2 = ts$Y[,2],
      batch = bat
    )
    return(df)
  }else{
    stop("`data` must be a data.frame, matrix, or a list of those.")
  }
}

#' Plot t-SNE Embedding by Batch
#'
#' Creates a scatter plot of a two-dimensional t-SNE embedding, colored by
#' batch or site.
#'
#' @param tsne_prep_result A data frame returned by [tsne_prep()].
#' @param ellipse Logical indicating whether to display batch-specific
#'   68-percent concentration ellipses. Defaults to `TRUE`.
#'
#' @return A `ggplot` object.
#'
#' @export
tsne_plot <- function(tsne_prep_result, ellipse = TRUE){
  element_names <- colnames(tsne_prep_result)
  plt <- ggplot(
    tsne_prep_result,
    aes(x = .data[["dim1"]], y = .data[["dim2"]], color = .data[["batch"]])
  ) +
    geom_point(alpha = 0.7, size = 1.6, stroke = 0) +
    coord_equal() +
    labs(
      x = "Dim 1",
      y = "Dim 2",
      color = "Batch / Site"
    ) +
    scale_color_brewer(palette = "Set2") +   # or: scale_color_viridis_d()
    theme_minimal(base_size = 12) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(linewidth = 0.2),
      strip.text = element_text(face = "bold"),
      strip.background = element_rect(fill = "grey95", color = NA),
      legend.position = "bottom",
      legend.title = element_text(face = "bold"),
      plot.title.position = "plot",
      panel.spacing = unit(6, "pt"),
      axis.title = element_text(face = "bold")
    )
  if(ellipse){
    plt + stat_ellipse(level = 0.68, linewidth = 0.6, show.legend = FALSE)
  }else{
    plt
  }
}


#' Construct a Model Matrix for a Variable Block
#'
#' Converts a data frame of variables into a numeric design matrix, removing
#' constant variables and the intercept.
#'
#' @param df A data frame or object coercible to a data frame.
#'
#' @return A numeric model matrix with non-constant encoded variables.
#'
#' @export
make_model_matrix_block <- function(df) {
  df <- as.data.frame(df)
  keep <- vapply(df, function(x) length(unique(x[!is.na(x)])) > 1L, logical(1))
  df <- df[, keep, drop = FALSE]
  if (ncol(df) == 0L) {return(matrix(numeric(0), nrow = nrow(df), ncol = 0L))}
  X <- stats::model.matrix(~ ., data = df)
  if ("(Intercept)" %in% colnames(X)) {X <- X[, colnames(X) != "(Intercept)", drop = FALSE]}
  X
}

#' Compute Association with a Single Variable
#'
#' Fits a linear model relating a surrogate variable to one metadata variable
#' and returns the corresponding coefficient of determination.
#'
#' @param y Numeric outcome vector.
#' @param x Predictor variable.
#' @param var_name Character name of the predictor.
#' @param panel_name Character label identifying the variable group.
#'
#' @return A one-row data frame containing the variable name, panel, and
#'   model \eqn{R^2}.
#'
#' @export
assoc_one <- function(y, x, var_name, panel_name) {
  dat <- data.frame(y = y, x = x)
  fit <- stats::lm(y ~ x, data = dat)
  s <- summary(fit)
  data.frame(
    SV = NA_character_,
    Variable = var_name,
    Panel = panel_name,
    R2 = unname(s$r.squared),
    stringsAsFactors = FALSE
  )
}


#' Summarize Surrogate-Variable Associations
#'
#' Computes associations between surrogate variables and batch or biological
#' covariates using feature-wise \eqn{R^2} values.
#'
#' @param H Numeric matrix of surrogate variables, with observations in rows.
#' @param batch_df Optional data frame of batch or technical variables.
#' @param cov_df Optional data frame of biological or other covariates.
#'
#' @return A data frame containing surrogate-variable names, metadata
#'   variables, variable groups, and \eqn{R^2} values.
#'
#' @export
sv_assoc_table <- function(H, batch_df = NULL, cov_df = NULL) {
  H <- as.matrix(H)
  sv_names <- colnames(H)
  if (is.null(sv_names)) {sv_names <- paste0("SV", seq_len(ncol(H)))}

  out <- list()

  if (!is.null(batch_df)) {
    batch_df <- as.data.frame(batch_df)
    for (k in seq_len(ncol(H))) {
      for (j in seq_len(ncol(batch_df))) {
        tmp <- assoc_one(H[, k], batch_df[[j]], colnames(batch_df)[j], "Batch variables")
        tmp$SV <- sv_names[k]
        out[[length(out) + 1L]] <- tmp
      }
    }
  }

  if (!is.null(cov_df)) {
    cov_df <- as.data.frame(cov_df)
    for (k in seq_len(ncol(H))) {
      for (j in seq_len(ncol(cov_df))) {
        tmp <- assoc_one(H[, k], cov_df[[j]], colnames(cov_df)[j], "Covariates")
        tmp$SV <- sv_names[k]
        out[[length(out) + 1L]] <- tmp
      }
    }
  }

  dplyr::bind_rows(out)
}

#' Plot Surrogate-Variable Associations
#'
#' Creates a heatmap of \eqn{R^2} associations between surrogate variables
#' and batch, technical, or biological variables.
#'
#' @param assoc_df A data frame returned by [sv_assoc_table()].
#'
#' @return A `ggplot` object.
#'
#' @export
plot_sv_assoc_heatmap <- function(assoc_df) {

  assoc_df <- assoc_df %>% mutate(
      SV = factor(.data[["SV"]], levels = rev(unique(.data[["SV"]]))),
      Variable = factor(.data[["Variable"]], levels = unique(.data[["Variable"]]))
    )

  ggplot(assoc_df, aes(x = .data[["Variable"]], y = .data[["SV"]], fill = .data[["R2"]])) +
    geom_tile(
      color = "white",
      linewidth = 0.8
    ) +
    geom_text(aes(label = sprintf("%.2f", .data[["R2"]])), size = 4, fontface = "bold") +
    facet_grid(. ~ Panel, scales = "free_x", space = "free_x") +
    scale_fill_gradientn(
      colours = c(
        "#F7FBFF",
        "#DDEBF7",
        "#9ECAE1",
        "#4292C6",
        "#084594"
      ),
      limits = c(0, max(assoc_df$R2, na.rm = TRUE)),
      name = expression(R^2)
    ) +
   labs(
      title = "Association of surrogate variables with technical and biological factors",
      subtitle = expression(
        "Cell values show the variance in each surrogate variable explained by each factor (" * R^2 * ")"
      ),
      x = NULL,
      y = NULL
    ) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
          strip.background = element_blank(),
          strip.text = element_text(face = "bold", size = 11, margin = margin(b = 6)),
      axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 11),
      axis.text.y = element_text(size = 11, face = "bold"),
      plot.title = element_text(face = "bold", size = 16, hjust = 0),
      plot.subtitle = element_text(size = 11, margin = margin(b = 10)),
      legend.position = "right",
      legend.title = element_text(face = "bold"),
      panel.spacing.x = grid::unit(1.2, "lines"),
      plot.margin = margin(10, 15, 10, 10)
    )
}


#' Canonical Correlation Diagnostic
#'
#' Performs canonical correlation analysis between surrogate variables and a
#' block of explanatory variables after removing constant and linearly
#' dependent columns.
#'
#' @param H Numeric matrix of surrogate variables.
#' @param X_block Data frame or matrix containing a block of explanatory
#'   variables.
#' @param tol Numeric tolerance used to identify near-constant and
#'   linearly dependent columns. Defaults to `1e-8`.
#'
#' @return A list containing canonical correlations, canonical scores,
#'   loadings, retained variables, matrix ranks, and complete-case indicators.
#'
#' @export
cca_diagnostic <- function(H, X_block, tol = 1e-8) {
  H <- as.matrix(H)
  X_block <- as.data.frame(X_block)
  X <- make_model_matrix_block(
    X_block
  )
  keep_rows <- stats::complete.cases(H, X)

  H <- H[keep_rows,,drop = FALSE]
  X <- X[keep_rows,,drop = FALSE]
  keep_H <- apply(H, 2, stats::sd) > tol
  keep_X <- apply(X, 2, stats::sd) > tol
  H <- H[,keep_H,drop = FALSE]
  X <- X[,keep_X,drop = FALSE]

  if (ncol(H) == 0L) {
    stop("No non-constant columns remain in `H`.")
  }

  if (ncol(X) == 0L) {
    stop("No non-constant columns remain in `X_block`.")
  }

  Hs <- scale(H); Xs <- scale(X)

  qr_H <- qr(Hs, tol = tol)
  rank_H <- qr_H$rank
  keep_H_idx <- qr_H$pivot[seq_len(rank_H)]
  Hs_red <- Hs[, keep_H_idx,drop = FALSE]

  qr_X <- qr(Xs, tol = tol)
  rank_X <- qr_X$rank
  keep_X_idx <- qr_X$pivot[seq_len(rank_X)]
  Xs_red <- Xs[, keep_X_idx,drop = FALSE]

  cc <- stats::cancor(Hs_red,Xs_red)

  U <- Hs_red %*% cc$xcoef
  V <- Xs_red %*% cc$ycoef

  colnames(U) <- paste0("U", seq_len(ncol(U)))
  colnames(V) <- paste0("V", seq_len(ncol(V)))

  sv_loadings <- stats::cor(Hs_red, U)
  technical_loadings <- stats::cor(Xs_red,V)

  list(
    cancor = cc,
    cor = cc$cor,
    U = U,
    V = V,
    sv_loadings = sv_loadings,
    block_loadings = technical_loadings,
    H_used = Hs_red,
    X_used = Xs_red,
    H_columns = colnames(Hs_red),
    X_columns = colnames(Xs_red),
    rank_H = rank_H,
    rank_X = rank_X,
    keep_rows = keep_rows
  )
}

#' Plot Canonical Correlations
#'
#' Compares canonical correlations between surrogate variables and batch or
#' technical variables versus biological covariates.
#'
#' @param cca_batch A result from [cca_diagnostic()] for batch or technical
#'   variables.
#' @param cca_cov A result from [cca_diagnostic()] for biological covariates.
#'
#' @return A `ggplot` object.
#'
#' @export
plot_cca_cor <- function(cca_batch, cca_cov) {
  df <- dplyr::bind_rows(
    data.frame(
      Dimension = seq_along(cca_batch$cor),
      Correlation = cca_batch$cor,
      Block = "Batch / technical"
    ),
    data.frame(
      Dimension = seq_along(cca_cov$cor),
      Correlation = cca_cov$cor,
      Block = "Biological covariates"
    )
  )

  ggplot(df, aes(x = .data[["Dimension"]], y = .data[["Correlation"]], color = .data[["Block"]], group = .data[["Block"]])) +
    geom_point(size = 3, stroke = 0.4) +
    geom_line(linewidth = 0.9, alpha = 0.85) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.2), expand = ggplot2::expansion(mult = c(0.01, 0.03))) +
    labs(
      x = "Canonical dimension",
      y = "Canonical correlation",
      color = NULL
    ) +
    theme_minimal(base_size = 14) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey90", linewidth = 0.4),
      axis.text = element_text(color = "grey25"),
      axis.title = element_text(color = "grey15"),
      plot.title = element_text(face = "bold", size = 15, margin = margin(b = 10)),
      legend.position = "top",
      legend.justification = "left",
      legend.text = element_text(size = 11),
      plot.margin = margin(10, 12, 8, 8)
    )
}

#' Plot Canonical Scores
#'
#' Creates a scatter plot of the first two surrogate-variable-side canonical
#' variates, colored by a user-specified variable.
#'
#' @param cca_obj A result returned by [cca_diagnostic()].
#' @param color_var A vector used to color observations in the plot.
#' @param title Optional plot title.
#'
#' @return A `ggplot` object.
#'
#' @export
plot_cca_scores <- function(cca_obj, color_var, title = NULL) {
  df <- data.frame(
    U1 = cca_obj$U[, 1],
    U2 = cca_obj$U[, 2],
    color_var = color_var
  )

  ggplot(df, aes(x = .data[["U1"]], y = .data[["U2"]], color = .data[["color_var"]])
  ) +
    geom_point(size = 2.7, alpha = 0.75) +
    labs(
      title = title,
      x = "SV-side canonical variate 1",
      y = "SV-side canonical variate 2",
      color = "Group"
    ) +
    theme_minimal(base_size = 14) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(color = "grey92", linewidth = 0.4),
      axis.text = element_text(color = "grey25", size = 10.5, face = "bold"),
      axis.title = element_text(color = "grey15", size = 12, face = "bold"),
      plot.title = element_text(face = "bold", size = 15, margin = margin(b = 10)),
      legend.title = element_text(face = "bold", size = 11),
      legend.text = element_text(size = 10),
      plot.margin = margin(10, 12, 8, 8))
}

#' Compute R-Squared for a Single Association
#'
#' Fits a linear model between two variables and returns the coefficient of
#' determination.
#'
#' @param y Numeric outcome vector.
#' @param x Predictor variable.
#'
#' @return A numeric \eqn{R^2} value, or `NA` when the association cannot be
#'   estimated.
#'
#' @export
get_r2 <- function(y, x) {
  keep <- stats::complete.cases(y, x)
  y <- y[keep]
  x <- x[keep]

  if (length(y) < 3L) {return(NA_real_)}
  if (length(unique(x)) <= 1L) {return(NA_real_)}

  dat <- data.frame(y = y, x = x)
  fit <- stats::lm(y ~ x, data = dat)
  unname(summary(fit)$r.squared)
}

#' Summarize Principal-Component Associations
#'
#' Performs PCA on the input data and computes the association between each
#' selected principal component and each metadata variable using \eqn{R^2}.
#'
#' @param data Numeric matrix with observations in rows and features in
#'   columns.
#' @param metadata Data frame containing metadata variables.
#' @param n_pc Number of principal components to evaluate. Defaults to `5`.
#' @param scale_data Logical indicating whether variables should be scaled
#'   before PCA. Defaults to `TRUE`.
#' @param variable_groups Optional named vector assigning metadata variables
#'   to display groups.
#'
#' @return A data frame containing metadata variables, principal components,
#'   and \eqn{R^2} values. PCA variance proportions and the fitted PCA object
#'   are stored as attributes.
#'
#' @export
pc_assoc_table <- function(
    data,
    metadata,
    n_pc = 5,
    scale_data = TRUE,
    variable_groups = NULL
) {

  data <- as.matrix(data)
  metadata <- as.data.frame(metadata)

  if (nrow(data) != nrow(metadata)) {
    stop("`data` and `metadata` must have the same number of rows.", call. = FALSE)
  }

  pca <- stats::prcomp(data, center = TRUE, scale. = scale_data)
  n_pc <- min(n_pc, ncol(pca$x))
  scores <- pca$x[, seq_len(n_pc), drop = FALSE]

  out <- list()
  idx <- 1L
  for (j in seq_len(ncol(metadata))) {
    var_name <- colnames(metadata)[j]
    x <- metadata[[j]]
    if (is.character(x)) {x <- as.factor(x)}
    for (k in seq_len(n_pc)) {
      r2 <- get_r2(y = scores[, k], x = x)
      out[[idx]] <- data.frame(
        Variable = var_name,
        PC = paste0("PC", k),
        R2 = r2,
        stringsAsFactors = FALSE
      )
      idx <- idx + 1L
    }
  }

  result <- do.call(rbind, out)

  if (!is.null(variable_groups)) {
    if (is.null(names(variable_groups))) {
      stop("`variable_groups` must be a named vector.", call. = FALSE)
    }
    result$Panel <- variable_groups[result$Variable]
  } else {
    result$Panel <- "Metadata"
  }

  pc_var <- pca$sdev^2 / sum(pca$sdev^2)

  attr(result, "pc_variance") <- pc_var[seq_len(n_pc)]
  attr(result, "pca") <- pca
  result
}

#' Plot Principal-Component Associations
#'
#' Creates a heatmap of associations between principal components and metadata
#' variables. Principal-component labels include the proportion of total
#' variance explained.
#'
#' @param assoc_df A data frame returned by [pc_assoc_table()].
#' @param title Character string specifying the plot title.
#'
#' @return A `ggplot` object.
#'
#' @export
plot_pc_assoc_heatmap <- function(
    assoc_df,
    title = "Association of principal components with metadata"
) {

  pc_var <- attr(assoc_df, "pc_variance")
  pc_levels <- paste0("PC", seq_along(pc_var))
  pc_labels <- paste0(pc_levels, "\n(", sprintf("%.1f%%", 100 * pc_var), ")")
  assoc_df$PC <- factor(assoc_df$PC, levels = pc_levels, labels = pc_labels)
  assoc_df$Variable <- factor(assoc_df$Variable, levels = rev(unique(assoc_df$Variable)))
  fill_max <- max(assoc_df$R2, na.rm = TRUE)

  ggplot(assoc_df, aes(x = .data[["PC"]], y = .data[["Variable"]], fill = .data[["R2"]])) +
    geom_tile(color = "white", linewidth = 0.5) +
    geom_text(aes(label = ifelse(is.na(.data[["R2"]]), "", sprintf("%.2f", .data[["R2"]]))), size = 3.6, color = "grey15",fontface = "bold") +
    facet_grid(Panel ~ ., scales = "free_y", space = "free_y") +
    scale_fill_gradientn(
      colours = c("#F7FBFF", "#DDEBF7", "#9ECAE1", "#4292C6", "#08519C"),
      limits = c(0, fill_max),
      name = expression(R^2)) +
    labs(title = title,
      subtitle = "Cell values show variance in each principal component explained by each metadata variable",
      x = "Principal component\n(% total imaging variance explained)",
      y = NULL) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
      strip.background = element_blank(),
      strip.text.y = element_text(face = "bold", size = 11, color = "grey20", margin = margin(r = 8)),
      axis.text.x = element_text(face = "bold", size = 10, color = "grey20", lineheight = 0.95),
      axis.text.y = element_text(size = 10, color = "grey25"),
      axis.title.x = element_text(size = 11.5, margin = margin(t = 8)),
      plot.title = element_text(face = "bold", size = 15, margin = margin(b = 5)),
      plot.subtitle = element_text(size = 10.5, color = "grey35", margin = margin(b = 10)),
      legend.title = element_text(face = "bold", size = 11),
      legend.text = element_text(size = 9.5),
      panel.spacing.y = grid::unit(0.8, "lines"),
      plot.margin = margin(10, 15, 10, 10)
    )
}



