#' Residualize an outcome matrix with respect to a design matrix
#'
#' Removes the linear variation in \code{Y} that is explained by the columns
#' of the design matrix \code{Z}. Residualization is performed using a QR
#' decomposition of \code{Z}, and the returned matrix contains the residuals
#' after projecting \code{Y} onto the orthogonal complement of the column
#' space of \code{Z}.
#'
#' This function is used to remove variation associated with specified
#' observed covariates before estimating additional latent structure. In the
#' harmonization framework, \code{Z} may represent biological effects or
#' other observed variables whose contribution should first be accounted for
#' when estimating residual variation.
#'
#' @param Y Numeric matrix containing the outcomes to be residualized, with
#'   observations in rows and features or variables in columns.
#'
#' @param Z Numeric design matrix containing the covariates whose linear
#'   effects should be removed from \code{Y}. The number of rows in
#'   \code{Z} must match the number of rows in \code{Y}.
#'
#' @return A numeric matrix with the same dimensions as \code{Y}, containing
#'   the residuals after removing the component of \code{Y} explained by
#'   the column space of \code{Z}.
#'
#' @keywords internal
residualize_one <- function(Y, Z) {
  Z <- as.matrix(Z)
  Y <- as.matrix(Y)
  if (any(is.na(Z)) || any(is.na(Y))) {
    stop("NA values found in data or design matrix during residualization.")
  }
  qr_Z <- qr(Z)
  R <- qr.resid(qr_Z, Y)
  return(R)
}

#' Permute residuals within subjects on a feature-by-feature basis
#'
#' Randomly permutes the residual values in \code{R} within each subject,
#' independently for each feature. This preserves the subject-level grouping
#' structure while disrupting the within-subject ordering or association of
#' residual values for each feature.
#'
#' For subjects with at least two observations, residual values are randomly
#' reordered across that subject's observations. Subjects with only one
#' observation are left unchanged. The permutation is performed separately
#' for each feature, so different features generally receive different
#' within-subject permutations.
#'
#' This type of permutation is useful when constructing a null distribution
#' while respecting repeated-measures or longitudinal clustering by subject.
#'
#' @param R Numeric matrix of residuals, with observations in rows and
#'   features in columns.
#'
#' @param subj_vec Vector of subject identifiers corresponding to the rows of
#'   \code{R}. Its length must equal the number of rows in \code{R}.
#'
#' @return A numeric matrix with the same dimensions as \code{R}, containing
#'   feature-wise residual values permuted independently within each subject.
#'
#' @keywords internal
permute_within_subject_featurewise <- function(R, subj_vec) {
  R <- as.matrix(R)
  subj_vec <- as.character(subj_vec)
  stopifnot(length(subj_vec) == nrow(R))
  idx_by_subj <- split(seq_len(nrow(R)), subj_vec)
  R_star <- R
  p <- ncol(R)
  for (g in seq_len(p)) {
    for (sid in names(idx_by_subj)) {
      idx <- idx_by_subj[[sid]]
      if (length(idx) >= 2) {
        R_star[idx, g] <- R[sample(idx), g]
      } else {
        R_star[idx, g] <- R[idx, g]
      }
    }
  }
  R_star
}


#' Detect the number of latent factors using permutation-based SVD testing
#'
#' Estimates the number of latent factors supported by the residual matrix
#' \code{R} using a permutation-based test on the proportion of residual
#' variation explained by successive singular values.
#'
#' The maximum number of candidate latent factors is restricted by both the
#' residual degrees of freedom after accounting for the protected design
#' matrix \code{Z} and the number of features in \code{R}. Specifically, the
#' candidate dimension is
#' \code{min(n - rank(Z), ncol(R))}.
#'
#' For each candidate singular component, the observed test statistic is the
#' proportion of total residual sum of squares explained by that singular
#' value. A null distribution is generated by independently permuting the
#' observations within each feature of \code{R}, thereby disrupting
#' cross-feature dependence while preserving each feature's marginal
#' distribution. The singular-value proportions are recalculated for each
#' permuted data set.
#'
#' Empirical p-values are computed as the proportion of permutation-based
#' statistics greater than or equal to the corresponding observed statistic.
#' To enforce sequential selection of latent factors, the p-values are made
#' nondecreasing across successive singular components. The estimated number
#' of latent factors, \code{K}, is then defined as the number of sequential
#' components with p-values below \code{alpha}.
#'
#' If no residual degrees of freedom are available, or if the residual matrix
#' contains essentially no variation, no latent factors are selected.
#'
#' @param R Numeric residual matrix, with observations in rows and features
#'   in columns. This matrix typically contains variation remaining after
#'   accounting for the observed effects represented by the protected design.
#'
#' @param Z Numeric protected design matrix used to determine the residual
#'   degrees of freedom available for latent-factor estimation.
#'
#' @param B Integer. Number of permutations used to construct the empirical
#'   null distribution. Larger values provide more stable p-value estimates
#'   at increased computational cost. Defaults to \code{50}.
#'
#' @param alpha Numeric. Significance threshold used to determine the number
#'   of retained latent factors. Defaults to \code{0.10}.
#'
#' @return A list with the following components:
#' \describe{
#'   \item{\code{K}}{Integer giving the estimated number of latent factors.}
#'   \item{\code{pvals}}{Empirical permutation p-values for the candidate
#'     singular components, after enforcing a nondecreasing sequence across
#'     components.}
#'   \item{\code{svd}}{The singular value decomposition of the original
#'     residual matrix \code{R}, as returned by \code{svd}.}
#' }
#'
#' @keywords internal
detect_K_one <- function(R, Z, B = 50, alpha = 0.10) {
  R <- as.matrix(R)
  Z <- as.matrix(Z)
  n <- nrow(R)
  p <- ncol(R)
  r_resid <- n - qr(Z)$rank
  r <- min(r_resid, p)

  if (r <= 0) {
    return(list(K = 0L, pvals = NA, svd = svd(R)))
  }

  svd_R <- svd(R)
  d <- svd_R$d[1:r]
  tot_var <- sum(d^2)
  if (tot_var <= .Machine$double.eps) {
    return(list(K = 0L, pvals = rep(NA_real_, r), svd = svd_R))
  }

  Tk <- d^2 / tot_var
  null_T <- matrix(NA_real_, nrow = B, ncol = r)
  qr_Z <- qr(Z)
  for (b in seq_len(B)) {
    R_star <- apply(R, 2, sample)
    R_star <- qr.resid(qr_Z, R_star)
    d_star <- svd(R_star, nu = 0, nv = 0)$d[seq_len(r)]
    denom  <- sum(d_star^2)
    null_T[b, ] <- if (denom <= .Machine$double.eps) rep(0, r) else d_star^2 / denom
  }

  pvals <- sapply(seq_len(r), function(k) {
    v <- null_T[, k]
    v <- v[is.finite(v)]
    if (length(v) == 0L) 1 else mean(v >= Tk[k])
  })

  for (k in 2:r) pvals[k] <- max(pvals[k-1], pvals[k])
  K <- sum(pvals < alpha)
  K <- if (!is.finite(K)) 0L else K
  list(K = as.integer(K), pvals = pvals, svd = svd_R)
}

#' Construct surrogate variables from residual latent structure
#'
#' Constructs \code{K} surrogate variables from the residual matrix \code{R}
#' using the leading left singular vectors of the residual SVD as initial
#' latent directions. For each candidate direction, features associated with
#' that direction are identified using feature-wise correlation tests with
#' Benjamini-Hochberg adjustment. The latent direction is then re-estimated
#' from the selected feature subset using singular value decomposition.
#'
#' Specifically, the first \code{K} left singular vectors of \code{R} are
#' used as provisional surrogate-variable directions. For each direction,
#' correlations between the direction and every feature in \code{R} are
#' tested. Features with BH-adjusted p-values below 0.10 are retained. If
#' fewer than 10 features satisfy this criterion, the function instead uses
#' up to the 200 features with the largest absolute correlations.
#'
#' An SVD is then performed on the centered selected-feature matrix, and the
#' left singular vector most strongly correlated in absolute value with the
#' corresponding provisional direction is chosen as the refined surrogate
#' variable.
#'
#' @param R Numeric residual matrix, with observations in rows and features
#'   in columns. This matrix typically represents variation remaining after
#'   accounting for observed effects that are protected in the main model.
#'
#' @param K Integer. Number of surrogate variables to construct.
#'
#' @param svd_R Singular value decomposition of \code{R}, typically obtained
#'   from \code{svd(R)} or returned by the latent-dimension detection step.
#'
#' @return A numeric matrix with \code{nrow(R)} rows and \code{K} columns.
#'   Each column contains one constructed surrogate variable. Columns are
#'   named \code{SV1}, \code{SV2}, ..., \code{SVK}.
#'
#' @keywords internal
construct_svs_one <- function(R, K, svd_R) {
  n <- nrow(R)
  p <- ncol(R)
  E1 <- svd_R$u[, 1:K, drop = FALSE]
  H <- matrix(NA_real_, nrow = n, ncol = K)
  for (k in seq_len(K)) {
    e_k <- E1[, k]
    cors <- apply(R, 2, function(x) cor(x, e_k))
    cors[!is.finite(cors)] <- 0
    n_eff <- n - 2
    tstat <- cors * sqrt(n_eff) / sqrt(1 - cors^2)
    pvals <- 2 * pt(-abs(tstat), df = n_eff)
    qvals <- p.adjust(pvals, method = "BH")
    sel <- which(qvals < 0.10)
    if (length(sel) < 10) {sel <- order(abs(cors), decreasing = TRUE)[1:min(200, p)]}
    R_sub <- R[, sel, drop = FALSE]
    R_sub <- scale(R_sub, center = TRUE, scale = FALSE)
    svd_sub <- svd(R_sub)
    U_sub   <- svd_sub$u
    if (ncol(U_sub) == 0) {H[, k] <- e_k} else {
      cands <- apply(U_sub, 2, function(v) cor(v, e_k))
      cands[!is.finite(cands)] <- 0
      best <- which.max(abs(cands))
      H[, k] <- U_sub[, best]
    }
  }

  colnames(H) <- paste0("SV", seq_len(K))
  H
}



#' Remove variation explained by surrogate variables
#'
#' Removes the component of the outcome matrix \code{Y} that is linearly
#' explained by the surrogate-variable matrix \code{H}. The surrogate-variable
#' coefficients are estimated by least squares using a QR decomposition, and
#' the fitted contribution of \code{H} is subtracted from \code{Y}.
#'
#' Conceptually, the function fits
#'
#' \deqn{Y = H A + E,}
#'
#' where \eqn{A} contains feature-specific surrogate-variable coefficients,
#' and returns
#'
#' \deqn{Y_{\mathrm{clean}} = Y - H \hat{A}.}
#'
#' @param Y Numeric outcome matrix, with observations in rows and features
#'   in columns.
#'
#' @param H Numeric matrix of estimated surrogate variables or latent factors,
#'   with observations in rows and latent factors in columns. The number of
#'   rows must match the number of rows in \code{Y}.
#'
#' @return A numeric matrix with the same dimensions as \code{Y}, after
#'   removing the fitted contribution of the surrogate variables in
#'   \code{H}.
#'
#' @keywords internal
remove_sv_one <- function(Y, H) {
  H <- as.matrix(H)
  Y <- as.matrix(Y)
  qrH <- qr(H)
  coef <- qr.coef(qrH, Y)
  coef[is.na(coef)] <- 0
  Y - H %*% coef
}


#' Remove surrogate-variable effects while preserving specified covariate effects
#'
#' Removes variation in \code{Y} attributable to the surrogate variables
#' in \code{H} while preserving variation represented by the protected
#' design matrix \code{Z}. The protected covariates and surrogate variables
#' are fitted jointly, so the contribution attributed to \code{H} is
#' estimated conditional on \code{Z}.
#'
#' Specifically, the function fits the joint linear model
#'
#' \deqn{Y = Z B + H A + E,}
#'
#' where \eqn{B} contains coefficients for the protected design and
#' \eqn{A} contains coefficients for the surrogate variables. Only the
#' estimated surrogate-variable contribution,
#'
#' \deqn{H \hat{A},}
#'
#' is subtracted from the observed data. The returned matrix is therefore
#'
#' \deqn{Y_{\mathrm{clean}} = Y - H \hat{A},}
#'
#' so that variation associated with the protected design \code{Z} is not
#' explicitly removed.
#'
#' @param Y Numeric outcome matrix, with observations in rows and features
#'   in columns.
#'
#' @param Z Numeric protected design matrix containing observed effects whose
#'   contribution should be retained. In the harmonization framework, this
#'   typically represents biological effects specified for preservation in
#'   the main ComBat model and may also contain other protected covariates.
#'
#' @param H Numeric matrix of estimated surrogate variables or latent factors,
#'   with observations in rows and latent factors in columns.
#'
#' @return A numeric matrix with the same dimensions as \code{Y}, after
#'   subtracting the contribution attributed to \code{H} conditional on
#'   the protected design \code{Z}.
#'
#' @keywords internal
remove_sv_one_preserve_Z <- function(Y, Z, H) {
  Z <- as.matrix(Z)
  H <- as.matrix(H)
  ZH <- cbind(Z, H)
  q <- ncol(Z)
  qr_fit <- qr(ZH)
  coefs <- qr.coef(qr_fit, Y)
  coefs[is.na(coefs)] <- 0
  beta  <- coefs[1:q, , drop = FALSE]
  alpha <- coefs[(q + 1):nrow(coefs), , drop = FALSE]
  H_contrib <- H %*% alpha
  cleaned_data <- Y - H_contrib
  return(cleaned_data)
}

#' Apply permutation-based surrogate variable adjustment to one measurement
#'
#' Estimates and removes latent variation from a single outcome matrix using
#' residual-based surrogate variable analysis. Observed variation represented
#' by the design matrix \code{Z} is first removed before latent-factor
#' detection. The number of latent factors is selected using permutation-based
#' testing of the residual singular-value spectrum, and surrogate variables
#' are subsequently constructed from the detected residual structure.
#'
#' If \code{preserve_Z = TRUE}, the surrogate-variable effects are estimated
#' jointly with the protected design \code{Z}, and only the contribution
#' attributable to the surrogate variables is removed from the original data.
#' Otherwise, the surrogate variables are regressed directly on the original
#' data and their fitted contribution is removed.
#'
#' @param data_nb Numeric matrix containing one measurement, with observations
#'   in rows and features in columns.
#'
#' @param Z Optional numeric protected design matrix containing observed
#'   effects to account for before estimating latent variation. If
#'   \code{NULL}, an intercept-only design matrix is used.
#'
#' @param B Integer. Number of permutations used to estimate the null
#'   distribution for latent-dimension selection. Defaults to \code{50}.
#'
#' @param alpha Numeric. Significance threshold used to determine the number
#'   of retained latent factors. Defaults to \code{0.10}.
#'
#' @param preserve_Z Logical. If \code{TRUE}, latent effects are removed
#'   conditional on the protected design \code{Z}, so that variation
#'   represented by \code{Z} is preserved. Defaults to \code{FALSE}.
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{data_nb_sva}}{The adjusted outcome matrix after removal of
#'     the estimated surrogate-variable contribution.}
#'   \item{\code{H}}{Matrix of estimated surrogate variables. Returns
#'     \code{NULL} if no latent factors are detected.}
#'   \item{\code{K}}{Estimated number of latent factors.}
#'   \item{\code{pvals}}{Permutation-based p-values used for latent-dimension
#'     selection.}
#' }
#'
#' @keywords internal
sva_per_measurement_np <- function(
    data_nb,
    Z = NULL,
    B = 50,
    alpha = 0.10,
    preserve_Z = FALSE
) {

  Y <- as.matrix(data_nb)
  n <- nrow(Y)

  if (is.null(Z)) {
    Z <- matrix(1, nrow = n, ncol = 1L, dimnames = list(NULL, "(Intercept)"))
  } else {
    Z <- as.matrix(Z)
  }

  if (nrow(Z) != n) {
    stop("`Z` must have the same number of rows as `data_nb`.")
  }

  if (anyNA(Y) || anyNA(Z)) {
    stop("Missing values are not allowed in `data_nb` or `Z`.")
  }

  if (B < 1L) {
    stop("`B` must be a positive integer.")
  }

  if (!is.numeric(alpha) || length(alpha) != 1L || alpha <= 0 || alpha >= 1) {
    stop("`alpha` must be a number between 0 and 1.")
  }

  R <- residualize_one(Y = Y, Z = Z)
  det <- detect_K_one(R = R, Z = Z, B = B, alpha = alpha)
  K <- det$K
  message("Detected latent factors: K = ", K)

  if (K <= 0L) {
    return(
      list(
        data_nb_sva = Y,
        H = NULL,
        K = 0L,
        pvals = det$pvals
      )
    )
  }

  H <- construct_svs_one(R = R, K = K, svd_R = det$svd)

  if (isTRUE(preserve_Z)) {
    data_nb_sva <- remove_sv_one_preserve_Z(Y = Y, Z = Z, H = H)
  } else {
    data_nb_sva <- remove_sv_one(Y = Y, H = H)
  }

  list(
    data_nb_sva = data_nb_sva,
    H = H,
    K = K,
    pvals = det$pvals
  )
}


#' Select the number of latent variance components using parallel analysis
#'
#' Estimates the number of latent components supported by a residual matrix
#' using permutation-based parallel analysis of its singular-value spectrum.
#' The observed singular values are compared with component-specific
#' thresholds obtained from independently permuted versions of the residual
#' matrix.
#'
#' For each permutation, the values within each feature are randomly
#' reordered across observations, preserving the marginal distribution of
#' each feature while disrupting cross-feature dependence. Singular values
#' are then computed from each permuted matrix to form an empirical null
#' distribution for each component.
#'
#' A component is retained when its observed singular value exceeds the
#' specified quantile of the corresponding permutation null distribution.
#' The estimated number of components is the number of observed singular
#' values satisfying this criterion, up to \code{k_max}.
#'
#' @param Z_resid Numeric residual matrix, with observations in rows and
#'   features in columns. This matrix should contain the residual variation
#'   from which latent variance structure is to be identified.
#'
#' @param X_batch Optional numeric primary-batch design matrix, with
#'   observations in rows and batch indicators in columns. When supplied,
#'   each permuted residual matrix is residualized with respect to this design
#'   before calculating its singular values. If \code{NULL}, no additional
#'   residualization is performed. Defaults to \code{NULL}.
#'
#' @param k_max Integer. Maximum number of latent components to consider.
#'   The effective maximum is additionally restricted by the number of
#'   singular values available in \code{Z_resid}. Defaults to \code{8}.
#'
#' @param B_perm Integer. Number of feature-wise permutations used to
#'   construct the empirical null distribution of singular values.
#'   Defaults to \code{30}.
#'
#' @param quant Numeric. Quantile of the permutation null distribution used
#'   as the component-specific selection threshold. For example,
#'   \code{quant = 0.95} retains components whose singular values exceed the
#'   95th percentile of the corresponding null distribution. Defaults to
#'   \code{0.95}.
#'
#' @param seed Integer. Random seed used for reproducibility of the
#'   permutation procedure. Defaults to \code{1}.
#'
#' @return A list with the following components:
#' \describe{
#'   \item{\code{k}}{Integer giving the estimated number of retained latent
#'     components.}
#'   \item{\code{d_obs}}{Observed singular values for the candidate
#'     components.}
#'   \item{\code{thr}}{Component-specific permutation thresholds defined by
#'     the requested null quantile.}
#' }
#'
#' @keywords internal
select_k_var_parallel <- function(Z_resid,
                                  X_batch = NULL,
                                  k_max  = 8L,
                                  B_perm = 30L,
                                  quant  = 0.95,
                                  seed   = 1L) {
  Z_resid <- as.matrix(Z_resid)
  set.seed(seed)

  sv_obs <- svd(Z_resid, nu = 0, nv = 0)$d
  k_max  <- min(as.integer(k_max), length(sv_obs))

  if (k_max <= 0) {return(list(k = 0L, d_obs = numeric(0), thr = numeric(0)))}

  qr_batch <- if (!is.null(X_batch)) qr(as.matrix(X_batch)) else NULL

  null_d <- matrix(0, nrow = as.integer(B_perm), ncol = k_max)
  for (b in seq_len(as.integer(B_perm))) {
    Zp <- apply(Z_resid, 2, sample)
    if (!is.null(qr_batch)) {Zp <- qr.resid(qr_batch, Zp)}
    null_d[b, ] <- svd(Zp, nu = 0, nv = 0)$d[seq_len(k_max)]
  }

  thr <- apply(null_d, 2, stats::quantile, probs = quant, na.rm = TRUE)
  keep <- sv_obs[seq_len(k_max)] > thr

  k <- if (keep[1L]) {
    first_failure <- which(!keep)
    if (length(first_failure) == 0L) {k_max} else {first_failure[1L] - 1L}
  } else {0L}

  #k <- sum(sv_obs[seq_len(k_max)] > thr)

  list(
    k     = as.integer(max(0L, min(k, k_max))),
    d_obs = sv_obs[seq_len(k_max)],
    thr   = thr
  )
}



